package com.example.backend.TelegramBotsApi.contants;

import jakarta.persistence.AssociationOverride;

public enum STEP {
    START,START_MENU_WAITING
    ,ADDING_TERRITORY,ADDING_FIO_WAITING, ADDING_CATEGORY, ADDING_ADDRESS, ADDING_INN, ADD_CLIENT,
    ADD_ADDRESS_CONFIRM, PAGINATION_WAITING, BOT_NAME_CREATE, BOT_TOKEN_CREATE, ADDING_PHONE_CONFIRMATION
}
